### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by Immortality-IMT** [aaaasmile/Solitario#1]
I had to include /usr/include/SDL2/

sudo apt-get install libsdl2-dev

SDL_image.h - sudo apt-get install libsdl-image1.2-dev

change makefile to

IINCLUDES = \
	-I/usr/include/SDL2\
    -I/usr/include/SDL\

win_type_global.h:57:13: error: ‘CONST’ does not name a type

Alfter which there are too many errors to compile.
#ifdef _WIN32
    // Windows-specific code
    typedef CONST CHAR *LPCSTR, *PCSTR;
#else
    // Linux-specific code
    typedef const char *LPCSTR, *PCSTR;
#endif

**Comment by aaaasmile** [comment]
Yes you are right. At the moment the main source branch works only on windows (and only for Italian Special Solitaire). The last Linux version was in 2004, so it needs some adjustment. I will working on it.

**Comment by Immortality-IMT** [comment]
The instructions appear to be for a linux/unix filesystem, what compiler 
is used to compile the source?

Kind Regards

Tony

**Comment by aaaasmile** [comment]
The version tagged  2.0.1 includes SDL2. Compiled in Ubuntu 22.04 and Windows with Msys2.
