### ISSUE TITLE
Cannot find libini.h

### ISSUE THREAD

**Issue by Immortality-IMT** [aaaasmile/Solitario#5]
#include <lib.ini.h>

Can it be included in the project and removed from the makefile linker as I am unable to locate it. Compile in Linux to see if there are errors. It might be  libini.h  -  Header file of functions to
                                       manipulate an ini file.
                             -------------------
    begin                : Fri Apr 21 2000
    copyright            : (C) 2000 by Simon White
    email                : s_a_white@email.com
?

**Comment by aaaasmile** [comment]
Libini is now included in project source
